## CHANGE this to the name of your plugin.
name: Metallurgy

## CHANGE this to your username.
author: JRBros2346

## CHANGE this to a meaninful but short description of your plugin.
description: A Slimefun Addon with Realistic metallurgy!! No RTX or Shaders!! -By JRBros2346

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.CHANGEME.slimefunaddon.ExampleAddon

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/JRBros2346/Metallurgy

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun
